/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nabilacahyaning_;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author RPL 2
 */
public class aplikasi_bbm extends javax.swing.JFrame {
String angka="",jenis="",balik="",banyak,terimakasih="";
double b1,b2,b3,b4,u,p;
int    kembalian,bayar;
boolean inputUang = true, inputPembayaran = false;
    /**
     * Creates new form aplikasi_bbm
     */
    public aplikasi_bbm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        uang = new javax.swing.JTextField();
        dua = new javax.swing.JButton();
        satu = new javax.swing.JButton();
        tiga = new javax.swing.JButton();
        empat = new javax.swing.JButton();
        lima = new javax.swing.JButton();
        enam = new javax.swing.JButton();
        tujuh = new javax.swing.JButton();
        delapan = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        nol = new javax.swing.JButton();
        c = new javax.swing.JButton();
        pertamax = new javax.swing.JButton();
        dexlite = new javax.swing.JButton();
        solar = new javax.swing.JButton();
        pertalite = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sisa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        liter = new javax.swing.JTextField();
        bensin = new javax.swing.JTextField();
        pembayaran = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        proses = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        thk = new javax.swing.JLabel();
        sembilan1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bodoni MT Black", 2, 36)); // NOI18N
        jLabel1.setText("SPBU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Pengisian Bahan Bakar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("RP");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        uang.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        uang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                uangFocusGained(evt);
            }
        });
        uang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uangActionPerformed(evt);
            }
        });
        uang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                uangKeyPressed(evt);
            }
        });
        getContentPane().add(uang, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 190, -1));

        dua.setText("2");
        dua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duaActionPerformed(evt);
            }
        });
        getContentPane().add(dua, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 40, 20));

        satu.setText("1");
        satu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuActionPerformed(evt);
            }
        });
        getContentPane().add(satu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 40, 20));

        tiga.setText("3");
        tiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tigaActionPerformed(evt);
            }
        });
        getContentPane().add(tiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 40, 20));

        empat.setText("4");
        empat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empatActionPerformed(evt);
            }
        });
        getContentPane().add(empat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 40, 20));

        lima.setText("5");
        lima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limaActionPerformed(evt);
            }
        });
        getContentPane().add(lima, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 40, 20));

        enam.setText("6");
        enam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enamActionPerformed(evt);
            }
        });
        getContentPane().add(enam, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 40, 20));

        tujuh.setText("7");
        tujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tujuhActionPerformed(evt);
            }
        });
        getContentPane().add(tujuh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 40, 20));

        delapan.setText("8");
        delapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delapanActionPerformed(evt);
            }
        });
        getContentPane().add(delapan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 40, 20));

        hapus.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        hapus.setText("<-");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 40, 20));

        nol.setText("0");
        nol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nolActionPerformed(evt);
            }
        });
        getContentPane().add(nol, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 40, 20));

        c.setText("C");
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 40, 20));

        pertamax.setBackground(new java.awt.Color(0, 153, 153));
        pertamax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GAMBAR/pertamax 50px (1).png"))); // NOI18N
        pertamax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pertamaxActionPerformed(evt);
            }
        });
        getContentPane().add(pertamax, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 80, 70));

        dexlite.setBackground(new java.awt.Color(255, 102, 51));
        dexlite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GAMBAR/dexlite 50px (1).png"))); // NOI18N
        dexlite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dexliteActionPerformed(evt);
            }
        });
        getContentPane().add(dexlite, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 80, 70));

        solar.setBackground(new java.awt.Color(102, 102, 102));
        solar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GAMBAR/solar 50px (1).png"))); // NOI18N
        solar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solarActionPerformed(evt);
            }
        });
        getContentPane().add(solar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 80, 70));

        pertalite.setBackground(new java.awt.Color(153, 204, 0));
        pertalite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GAMBAR/pertalite 50px (1).png"))); // NOI18N
        pertalite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pertaliteActionPerformed(evt);
            }
        });
        getContentPane().add(pertalite, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 80, 70));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("JUMLAH PENGISIAN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 244, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("JENIS BAHAN BAKAR");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("PEMBAYARAN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 304, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("KEMBALIAN");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, 20));

        sisa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        sisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sisaActionPerformed(evt);
            }
        });
        getContentPane().add(sisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 170, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("RP");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("LITER");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        liter.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        liter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                literActionPerformed(evt);
            }
        });
        getContentPane().add(liter, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 170, -1));

        bensin.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        bensin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bensinActionPerformed(evt);
            }
        });
        getContentPane().add(bensin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 170, -1));

        pembayaran.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pembayaran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pembayaranFocusGained(evt);
            }
        });
        pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembayaranActionPerformed(evt);
            }
        });
        pembayaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pembayaranKeyPressed(evt);
            }
        });
        getContentPane().add(pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 170, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("RP");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        proses.setText("PROSES");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });
        getContentPane().add(proses, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, -1));

        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, -1, -1));

        thk.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        thk.setText(" ");
        getContentPane().add(thk, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 160, 30));

        sembilan1.setText("9");
        sembilan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sembilan1ActionPerformed(evt);
            }
        });
        getContentPane().add(sembilan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 40, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uangActionPerformed

    private void duaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duaActionPerformed
    if(inputPembayaran){
        angka +="2";
        pembayaran.setText(angka);
    }else{
        angka +="2";
        uang.setText(angka);
    }
    }//GEN-LAST:event_duaActionPerformed

    private void tigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tigaActionPerformed
    if(inputPembayaran){
        angka +="3";
        pembayaran.setText(angka);
    }else{
        angka +="3";
        uang.setText(angka);
    }
    }//GEN-LAST:event_tigaActionPerformed

    private void sisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sisaActionPerformed

    private void literActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_literActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_literActionPerformed

    private void bensinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bensinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bensinActionPerformed

    private void pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembayaranActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_pembayaranActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
    pembayaran.setText("");
    bensin.setText("");
    liter.setText("");
    sisa.setText("");
    angka ="";
    uang.setText("");
    thk.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void satuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuActionPerformed
    if(inputPembayaran){
        angka +="1";
        pembayaran.setText(angka);
    }else{
        angka +="1";
        uang.setText(angka);
    }
        
    }//GEN-LAST:event_satuActionPerformed

    private void empatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empatActionPerformed
    if(inputPembayaran){
        angka +="4";
        pembayaran.setText(angka);
    }else{
        angka +="4";
        uang.setText(angka);
    }
    }//GEN-LAST:event_empatActionPerformed

    private void limaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limaActionPerformed
    if(inputPembayaran){
        angka +="5";
        pembayaran.setText(angka);
    }else{
        angka +="5";
        uang.setText(angka);
    }
    }//GEN-LAST:event_limaActionPerformed

    private void enamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enamActionPerformed
    if(inputPembayaran){
        angka +="6";
        pembayaran.setText(angka);
    }else{
        angka +="6";
        uang.setText(angka);
    }
    }//GEN-LAST:event_enamActionPerformed

    private void tujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tujuhActionPerformed
    if(inputPembayaran){
        angka +="7";
        pembayaran.setText(angka);
    }else{
        angka +="7";
        uang.setText(angka);
    }
    }//GEN-LAST:event_tujuhActionPerformed

    private void delapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delapanActionPerformed
    if(inputPembayaran){
        angka +="8";
        pembayaran.setText(angka);
    }else{
        angka +="8";
        uang.setText(angka);
    }
    }//GEN-LAST:event_delapanActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
       if(inputPembayaran){
        StringBuffer erase = new StringBuffer(pembayaran.getText());
       erase.reverse();
       
       erase.deleteCharAt(0);
       erase.reverse();
       
       String x = new String(erase);
       pembayaran.setText(x);
       
        pembayaran.setText(x);
        angka = x;
    }else{
        StringBuffer erase = new StringBuffer(uang.getText());
       erase.reverse();
       
       erase.deleteCharAt(0);
       erase.reverse();
       
       String x = new String(erase);
       uang.setText(x);
       
        uang.setText(x);
        angka = x;
    }
    }//GEN-LAST:event_hapusActionPerformed

    private void nolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nolActionPerformed
    if(inputPembayaran){
        angka +="0";
        pembayaran.setText(angka);
    }else{
        angka +="0";
        uang.setText(angka);
    }
    }//GEN-LAST:event_nolActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
    angka ="";
        uang.setText("");
    }//GEN-LAST:event_cActionPerformed

    private void dexliteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dexliteActionPerformed
    jenis ="dexlite";
    bensin.setText(jenis);
    
    u = Double.parseDouble(uang.getText());
    b1 = u/17100;
    banyak = String.format("%.2f", b1);
//    String tes = String.format("%.2f", b1);
    liter.setText(banyak);
    }//GEN-LAST:event_dexliteActionPerformed

    private void solarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solarActionPerformed
    jenis ="solar";
    bensin.setText(jenis);
    
    u = Double.parseDouble(uang.getText());
    b1 = u/17100;
    banyak = String.format("%.2f", b1);
//    String tes = String.format("%.2f", b1);
    liter.setText(banyak);
    }//GEN-LAST:event_solarActionPerformed

    private void pertaliteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pertaliteActionPerformed
    jenis ="pertalite";
    bensin.setText(jenis);
    
    u = Double.parseDouble(uang.getText());
    b1 = u/10000;
     banyak = String.format("%.2f", b1);
//    String tes = String.format("%.2f", b1);
    liter.setText(banyak);
    }//GEN-LAST:event_pertaliteActionPerformed

    private void pertamaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pertamaxActionPerformed
    jenis ="pertamax";
    bensin.setText(jenis);
    
    u = Double.parseDouble(uang.getText());
    b1 = u/14500;
     banyak = String.format("%.2f", b1);
//    String tes = String.format("%.2f", b1);
    liter.setText(banyak);
    }//GEN-LAST:event_pertamaxActionPerformed

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
    u = Double.parseDouble(uang.getText());
    bayar = Integer.parseInt(pembayaran.getText());
    
    terimakasih = "TERIMAKASIH";
    thk.setText(terimakasih);
    
    kembalian = (int) (bayar - u);
    balik = Integer.toString(kembalian);
    sisa.setText(balik);
    
   
    }//GEN-LAST:event_prosesActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
    String ObjButtons[] = {"Yes" , "No"};
    int pilihan = JOptionPane.showOptionDialog(null,"Apakah Anda Yakin Ingin Keluar?", "Message", JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,ObjButtons,ObjButtons[1]);
    if(pilihan == 0){
        System.exit(0);
    }
    }//GEN-LAST:event_exitActionPerformed

    private void uangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uangKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_uangKeyPressed

    private void pembayaranKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pembayaranKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pembayaranKeyPressed

    private void pembayaranFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pembayaranFocusGained
        // TODO add your handling code here:
        inputUang = false;
        inputPembayaran = true;
        angka = pembayaran.getText();
        
    }//GEN-LAST:event_pembayaranFocusGained

    private void uangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_uangFocusGained
        // TODO add your handling code here:
        inputUang = true;
        inputPembayaran = false;
        angka = uang.getText();
    }//GEN-LAST:event_uangFocusGained

    private void sembilan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sembilan1ActionPerformed
        if(inputPembayaran){
            angka +="9";
            pembayaran.setText(angka);
        }else{
            angka +="9";
            uang.setText(angka);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_sembilan1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aplikasi_bbm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aplikasi_bbm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aplikasi_bbm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aplikasi_bbm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aplikasi_bbm().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bensin;
    private javax.swing.JButton c;
    private javax.swing.JButton clear;
    private javax.swing.JButton delapan;
    private javax.swing.JButton dexlite;
    private javax.swing.JButton dua;
    private javax.swing.JButton empat;
    private javax.swing.JButton enam;
    private javax.swing.JButton exit;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton lima;
    private javax.swing.JTextField liter;
    private javax.swing.JButton nol;
    private javax.swing.JTextField pembayaran;
    private javax.swing.JButton pertalite;
    private javax.swing.JButton pertamax;
    private javax.swing.JButton proses;
    private javax.swing.JButton satu;
    private javax.swing.JButton sembilan1;
    private javax.swing.JTextField sisa;
    private javax.swing.JButton solar;
    private javax.swing.JLabel thk;
    private javax.swing.JButton tiga;
    private javax.swing.JButton tujuh;
    private javax.swing.JTextField uang;
    // End of variables declaration//GEN-END:variables
}
